---
## Enable AppLocker in audit mode, Win Enterprise+
## https://technet.microsoft.com/en-us/library/dd759131(v=ws.11).aspx

## https://www.sixdub.net/?p=367
## https://dfir-blog.com/2016/01/03/protecting-windows-networks-applocker/
## http://www.scip.ch/en/?labs.20150507
## https://www.sysadmins.lv/blog-en/powershell-50-and-applocker-when-security-doesnt-mean-security.aspx
## block: {{ harden_win_temp_dir }}, C:\ProgramData, Recycle Bin
## block for non-admin users: Powershell+ddl? Deny: %SYSTEM32%\Windows\PowerShell\*

## https://insights.sei.cmu.edu/cert/2016/06/bypassing-application-whitelisting.html
## http://www.howtogeek.com/howto/8739/restrict-users-to-run-only-specified-programs-in-windows-7/
## https://www.bleepingcomputer.com/tutorials/create-an-application-whitelist-policy-in-windows/
## https://www.asd.gov.au/publications/protect/Hardening_Win7_SP1.pdf       13. list of path to whitelist
## Applocker to block program from
##  %USERPROFILE%, %ALLUSERSPROFILE%, %PUBLIC%, %OSDRIVE%\Users\*, %APPDATA%
##  %TEMP%, Recycler
##  %ProgramData%, %OSDRIVE%\Program Files\Common Files\Microsoft Shared\VBA\*
## https://github.com/MHaggis/hunt-detect-prevent/blob/master/Prevention/applocker.md
## https://github.com/MHaggis/hunt-detect-prevent/blob/master/Prevention/Applocker/applocker.xml

## powershell downgrade
## C:\WINDOWS\assembly\GAC_MSIL\System.Management.Automation
## C:\WINDOWS\assembly\NativeImages_v2.0.50727_64 or v2.0.*
