---
## https://docs.microsoft.com/en-us/windows/threat-protection/use-windows-event-forwarding-to-assist-in-instrusion-detection
## https://msdn.microsoft.com/en-us/library/cc748890(v=ws.11).aspx
## https://msdn.microsoft.com/en-us/library/bb870973(v=vs.85).aspx
## https://blogs.technet.microsoft.com/jepayne/2015/11/23/monitoring-what-matters-windows-event-forwarding-for-everyone-even-if-you-already-have-a-siem/
## https://blogs.technet.microsoft.com/wincat/2008/08/11/quick-and-dirty-large-scale-eventing-for-windows/

- name: Add wef collector server to Event Log readers local group
  win_user:
    name: "{{ harden_win_wef_collector_server }}"
    state: present
    groups_action: add
    groups:
      - Event Log Readers

- name: upload WEF configuration template
  win_template:
    src: WEF-Subscription.xml.j2
    dest: "{{ harden_win_temp }}\\WEF-Subscription.xml.j2"
    backup: yes

- name: Configure WEF subscription
  win_command: "wecutil cs {{ harden_win_temp }}\\WEF-Subscription.xml.j2"

