---
## Limitation on HKCU manipulation https://github.com/ansible/ansible/issues/20123

- include: windows-logging-registry.yml
#- include: windows-logging-wevtutil.yml

## https://technet.microsoft.com/en-ca/library/dn535776.aspx
- name: Enable ProcessCreationIncludeCmdLine_Enabled audit
  win_regedit:
    key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
    value: ProcessCreationIncludeCmdLine_Enabled
    data: 1
    datatype: dword

# http://blogs.technet.com/b/kfalde/archive/2015/10/02/emet-reporting.aspx
# https://github.com/kurtfalde/EMET-Reporting

## LSA hardening: Monitor: Operational log under Applications and Services Logs\Microsoft\Windows\CodeIntegrity, ID 3065, 3066, failure: 3033, 3063
## https://technet.microsoft.com/en-us/security/dn920237.aspx
## https://technet.microsoft.com/library/dn408187.aspx
- block:
    - name: LSA hardening (1)
      win_regedit:
        key: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\LSASS.exe
        value: AuditLevel
        data: 8
        datatype: dword
    - name: LSA hardening (2) - On x86-based or x64-based devices using Secure Boot and UEFI or not
      win_regedit:
        key: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        value: RunAsPPL
        data: 1
        datatype: dword
  when: harden_win_lsa_harden is defined and harden_win_lsa_harden

## https://www.sternsecurity.com/blog/local-network-attacks-llmnr-and-nbt-ns-poisoning
## https://www.tagi.wiki/advisories/smb-relay-how-we-leverage-it-and-how-you-can-stop-us
## http://windowsitpro.com/networking/q-how-can-i-disable-netbios-over-tcpip-windows-server-core-installations
## https://technet.microsoft.com/en-us/library/cc775874%28v=ws.10%29.aspx
- name: Disable Windows Link-Local Multicast Name Resolution (LLMNR)
  win_regedit:
    key: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
    value: EnableMulticast
    data: 0
    datatype: dword
### FIXME!
#- name: Disable Windows Netbios Name Service (NBT-NS)
##  win_regedit:
##  key: HKLM:\SYSTEM\CurrentControlSet\services\NetBT\Parameters\Interfaces\xxxGUIDxxx
##    value: NetbiosOptions
##    data: 2
##  command: "wmic /interactive:off nicconfig where TcpipNetbiosOptions={{ item }} call SetTcpipNetbios 2"
##  with_items:
##    - 0
##    - 1
#   command: 'powershell -Command "set-ItemProperty HKLM:SYSTEMCurrentControlSetservicesNetBTParametersInterfacestcpip* -Name NetbiosOptions -Value 2"'

## http://news.softpedia.com/news/how-to-prevent-zip-files-from-executing-malicious-javascript-behind-your-back-503226.shtml
## https://labsblog.f-secure.com/2016/04/19/how-to-disable-windows-script-host/
- name: disable Windows Script Host (1)
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
    value: Enabled
    data: 0
    datatype: dword
- name: disable Windows Script Host (2)
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
    value: IgnoreUserSettings
    data: 1
    datatype: dword
## not sure about this one?
#- name: Enable SAFER -  Software Restrictions Policies block scripts
#  win_regedit:
#    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
#    value: UseWinSAFER
#    data: 0

## https://bluesoul.me/2016/05/12/use-gpo-to-change-the-default-behavior-of-potentially-malicious-file-extensions/
## HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\
## \HKEY_CLASSES_ROOT\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts
## Partially covered if Windows Script Host is disabled
## FIXME! NOK
- name: disable suspicious executabled file extensions (HKCU)
  win_regedit:
#    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta
    key: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.{{ item }}"
#    key: "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.{{ item }}"    ## NOK
#    key: "HKLM:\\Software\\Exts\\.{{ item }}"    ## NOK
#    value: Enabled
    data: "%windir%\\system32\\notepad.exe"
  with_items: "{{ harden_win_suspicious_ext }}"

## Note: HKCR only applies if HKCU doesn't exist. better enforcing with GPO
- name: disable javascript execution by Windows Script Host (HKCR)
  win_regedit:
#    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta
    key: "{{ item }}"
    data: "%windir%\\system32\\notepad.exe %1"
  with_items:
    - "HKCR:\\htafile\\shell\\open\\command"
    - "HKCR:\\VBSFile\\shell\\open\\command"
    - "HKCR:\\JSFile\\shell\\open\\command"
    - "HKCR:\\scriptletfile\\shell\\open\\command"  ## default

## https://blogs.technet.microsoft.com/fdcc/2011/01/24/alwaysinstallelevated-is-equivalent-to-granting-administrative-rights/
## https://msdn.microsoft.com/en-us/library/windows/desktop/aa367561(v=vs.85).aspx
- name: Ensure Msiexec only executes with current user privileges
  win_regedit:
    key: HKLM:\Software\Policies\Microsoft\Windows\Installer
    value: AlwaysInstallElevated
    data: 0
    datatype: dword

- include: wpad-disable.yml
  when: harden_windows_disable_wpad is defined and harden_windows_disable_wpad

- name: Disable CMD
  win_regedit:
    key: HKCU:\Software\Policies\Microsoft\Windows\System
    value: DisableCMD
    datatype: dword
    data: 1
  when: harden_windows_disable_cmd

## https://onedrive.live.com/view.aspx?resid=A352EBC5934F0254!3316&ithint=file%2cpptx&app=PowerPoint
## https://support.microsoft.com/en-us/help/2871997/microsoft-security-advisory-update-to-improve-credentials-protection-and-management-may-13,-2014
- name: Win7/KB2871997 | trigger the clearing of any credentials of logged off users after 30 seconds
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    value: TokenLeakDetectDelaySecs
    datatype: dword
    data: 30

- include: windows-mimikatz.yml
