---

## https://www.asd.gov.au/publications/protect/hardening-ms-office-2016.htm
## https://www.asd.gov.au/publications/protect/ms-office-macro-security.htm
## http://www.asd.gov.au/publications/protect/Microsoft_Office_Macro_Security.pdf
## https://blogs.technet.microsoft.com/mmpc/2016/03/22/new-feature-in-office-2016-can-block-macros-and-help-prevent-infection/
## https://blogs.technet.microsoft.com/diana_tudor/2014/12/02/microsoft-project-how-to-control-macro-settings-using-registry-keys/
## https://technet.microsoft.com/en-us/library/cc179076.aspx    ActiveX in Office
## https://technet.microsoft.com/en-us/library/cc179039.aspx

- name: Ms Office | defined trusted locations path
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\{{ item }}\\Security\\Trusted Locations"
    name: Path
    data: "{{ harden_win_msoffice_trustedlocations }}"
    type: expandstring
  with_items:
    - Access
    - Excel
    - Outlook
    - PowerPoint
    - Visio
    - Word

## https://doublepulsar.com/oleoutlook-bypass-almost-every-corporate-security-control-with-a-point-n-click-gui-37f4cbc107d0
- name: Ms Office | silently disable OLE Package function in Outlook
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Outlook\\Security"
    name: ShowOLEPackageObj
    data: 0
    type: dword

## https://blogs.technet.microsoft.com/mmpc/2016/06/14/wheres-the-macro-malware-author-are-now-using-ole-embedding-to-deliver-malicious-files/
- name: Ms Office | Prevent activation of OLE packages
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\{{ item }}\\Security"
    name: PackagerPrompt
    data: "{{ harden_win_msoffice_packagerprompt }}"
    type: dword
  with_items:
    - Access
    - Excel
    - Outlook
    - PowerPoint
    - Visio

# https://www.endgame.com/blog/technical-blog/bug-feature-debate-back-yet-again-ddeauto-root-cause-analysis
# https://blog.barkly.com/microsoft-office-malware-attack-no-macros
# https://gist.github.com/wdormann/732bb88d9b5dd5a66c9f1e1498f31a1b
- name: Ms Office | Disable DDE - Link auto update
  win_regedit:
    key: "{{ item }}"
    name: DontUpdateLinks
    data: 1
    type: dword
  with_items:
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Word\\Options"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Word\\Options\\WordMail"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Excel\\Options"
  when: harden_win_msoffice_disable_dde_updatelink

- name: Ms Office | Disable DDE - OneNote DisableEmbeddedFiles
  win_regedit:
    key: "{{ item }}"
    name: DisableEmbeddedFiles
    data: 1
    type: dword
  with_items:
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\OneNote\\Options"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Word\\Options\\WordMail"
    - "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Excel\\Options"
  when: harden_win_msoffice_disable_dde_embeddedfiles

- name: Ms Office | Disable DDE - Excel extras
  win_regedit:
    key: "HKCU:\\Software\\Microsoft\\Office\\{{ harden_win_msoffice_version_reg }}\\Excel\\Options"
    name: "{{ item.n }}"
    data: "{{ item.d }}"
    type: dword
  with_items:
    - { n: "DDEAllowed", d: 0 }
    - { n: "DDECleaned", d: 1 }
    - { n: "Options", d: 117 }
  when: harden_win_msoffice_disable_dde_excel_extras
